### ISSUE TITLE
Messages column in overview is XML safe

### ISSUE THREAD

**Issue by Firesphere** [symbiote/silverstripe-queuedjobs#103]
Thus the whole `<ul><li>` thing is escaped and shown as literal in the Message column.
I've tried a few things, but to no avail yet.

(Also, GitHub parses HTML, apparently! :D )

**Comment by robbieaverill** [comment]
@Firesphere still a problem? Which version were you using?

**Comment by robbieaverill** [comment]
I've tested this on SilverStripe 4.2.0:

* The content in the Messages tab for a QueuedJobDescriptor is rendered in a list correctly
* The overview column in the descriptor GridField displays the text with no HTML

We're in critical bugfix and security only mode for SilverStripe 3, so I'm going to close this now. Feel free to reopen if you find an issue with this in 4.x =)
