### ISSUE TITLE
ProcessJobQueueTask remains in memory, causing issues after code deployment

### ISSUE THREAD

**Issue by mateusz** [symbiote/silverstripe-queuedjobs#105]
On CWP, using default queuedjobs settings, the `ProcessJobQueueTask` never exits in some cases. After a deployment, the worker is left behind using the old code which remains in-memory, while the site, database, solr schema etc. have already moved on. This causes weird, hard-to-debug fatal errors in many cases.

We have cases where the worker has been running for several months already. The problem isn't easy to notice because the worker keeps picking up new tasks. Did not have a chance to find the exact trigger, but in one case there were _Initialising_ jobs in the queue, in another there were _Broken_, _Cancelled_ and _Paused_, in yet another just _Broken_ and _Paused_.

I see two ways to resolve this:
- Make an explicit promise the worker will exit after the current batch is done.
- Expose an API for gracefully pausing and reloading the worker. This would allow us to pause jobs for the duration of deployment, and then reload when we are done.

I feel like the latter is better, because letting the worker run in parallel to the deployment seems like a recipe for trouble.

Here is how [php-resque](https://github.com/chrisboulton/php-resque/blob/3cead7dbb60a1389e647cc93d6fb795f2438d04c/lib/Resque/Worker.php#L349) does it.

**Comment by nyeholt** [comment]
What runner are you using ? Doorman?

**Comment by mateusz** [comment]
Default setup.

**Comment by mateusz** [comment]
Ok, so I decided to descend into the caves of async on my own. I'm attaching the log of the journey, with findings.

Turns out we are using `DoormanRunner` after all.

Strace shows the worker is stuck in the [runQueue loop](https://github.com/silverstripe-australia/silverstripe-queuedjobs/blob/master/code/tasks/engines/DoormanRunner.php#L51) (executing the "sleep 1" continuously). The stdout contains only:

```
[2016-11-01 15:16:32] No new jobs\n
```

There are no Waiting nor New jobs in the database, so the `$descriptor` must be null.

Independently, strace shows the worker is twice querying the database by filtering on ID - so either `unserialise` or `refreshDescriptor` or both. The job in the DB looks like follows:
```
*************************** 1. row ***************************
                ID: 19822
         ClassName: QueuedJobDescriptor
        LastEdited: 2016-10-27 10:57:05
           Created: 2016-10-27 10:57:03
          JobTitle: FullTextSearch Commit Job
         Signature: SearchUpdateCommitJobProcessor
    Implementation: SearchUpdateCommitJobProcessor
        StartAfter: NULL
        JobStarted: 2016-10-27 10:57:05
      JobRestarted: NULL
       JobFinished: 2016-10-27 10:57:05
        TotalSteps: 2
    StepsProcessed: 2
LastProcessedCount: -1
      ResumeCounts: 0
      SavedJobData: O:8:"stdClass":3:{s:7:"skipped";b:0;s:9:"completed";a:2:{i:0;s:9:"*****Index";i:1;s:15:"SolrSearchIndex";}s:7:"indexes";a:2:{i:0;s:9:"*****Index";i:1;s:15:"SolrSearchIndex";}}
  SavedJobMessages: a:5:{i:0;s:54:"[2016-10-27 10:57:05][INFO] Committing index *****Index";i:1;s:69:"[2016-10-27 10:57:05][INFO] Committing index *****Index was successful";i:2;s:60:"[2016-10-27 10:57:05][INFO] Committing index SolrSearchIndex";i:3;s:75:"[2016-10-27 10:57:05][INFO] Committing index SolrSearchIndex was successful";i:4;s:49:"[2016-10-27 10:57:05][INFO] All indexes committed";}
         JobStatus: Complete
           JobType: 2
           RunAsID: 17
```

From that we can guess that some combination of `unserialize`, `canRunTask`, or `isCancelled` is being called. Since the job is set to "Complete", both `canRunTask` and `isCancelled` will return false.

I'm guessing this means the job will [be requeued forever](https://github.com/asyncphp/doorman/blob/master/src/Manager/ProcessManager.php#L114), and thus `tick` will never return false.

This would fit with the `ProcessJobQueueTask` never exiting, which seems to be unintended.

Likely cause is two workers picking the job up at the same time, and then one of them completing, and the other getting stuck. Method that gets the task from the db is called `getNextJobDescriptorWithoutMutex` ;-) so I assume there is no built-in protection against race conditions.

I can't prove this is the case at the moment though, because the moment I restart the worker, the problem goes away ;-)

@nyeholt would it be a good fix to return true from `isCancelled` if the job is already `STATUS_COMPLETE`? This would prevent the job from being re-added to the waiting list, and would mean the `ProcessJobQueueTask` would exit immediately.

**Comment by mateusz** [comment]
Update: setting the offending job to JobStatus="Cancelled" caused the job to finish gracefully, so I guess it's some kind of a proof. I'm not sure whether the cause of the race condition is internal to queuedjobs, or external (due to our infrastructure).

**Comment by mateusz** [comment]
Thinking further, if this is indeed a correct description of the bug, I'd probably approach it from both sides:
- make sure the worker does not infinitely requeue completed job (to protect from other bugs)
- implement mutex on dequeue.

**Comment by robbieaverill** [comment]
I've made a PR implementing @mateusz's suggestion for fixing the infinitely running processes at #205. It's likely that the other idea "implement mutex on dequeue" will be looked at as part of #204, and I think if we still want to implement "Expose an API for gracefully pausing and reloading the worker." then we need a new enhancement issue for it
