### ISSUE TITLE
Running on Windows in Live mode fails

### ISSUE THREAD

**Issue by beedubsss** [symbiote/silverstripe-queuedjobs#106]
Hi,

I am using this module in a windows environment which is fine when the site is in 'dev' mode but once I switch it to live mode it does not run at all. I am using solr so occasionally I need to run /dev/task/Solr_Reindex but it never completes. If i switch to dev mode and run it i get the desired results. This does not just occur with other modules that use this as well. 

Cheers

**Comment by nyeholt** [comment]
Do you have any log output ?

**Comment by beedubsss** [comment]
@nyeholt I believe it is due to me running on windows and not having a cron job setup to handle the queue. As I have to use this on windows is there any other way to get doorman setup to process the queue in live environments?

**Comment by beedubsss** [comment]
After running /dev/task/ProcessJobQueueTask in the browser in live mode. I get this output

Running Task ProcessJobQueueTask
[2016-11-15 07:03:40] Running Some test job for 48 seconds and others from 2.
[2016-11-15 07:03:42] Running Solr Reindex Job and others from 2.

But it appears nothing completes, the admin interface just shoes initializing for the jobs

**Comment by robbieaverill** [comment]
@beedubsss if you're experiencing this still please feel free to reopen again
