### ISSUE TITLE
Email template doesn't apply theme

### ISSUE THREAD

**Issue by mikeyc7m** [symbiote/silverstripe-queuedjobs#112]
Not sure if this is module-specific but emails sent from within a queuedjob appear to be ignorant of the theme. For example I have a template called GenericEmail.ss in my theme but instead of using that it sends using the framework version. Pages & tasks are using the correct themed file, queuedjobs are not. 
`$data = $data->renderWith('SomeCustomTemplate');`
`$email->setTemplate('GenericEmail');`
`$email->populateTemplate(array('Body'=>$data));`
`$email->send(); `
I tried updating SSViewer config to specify the theme but it had no effect. SS3.2

**Comment by nyeholt** [comment]
It _shouldn't_ have any issue with picking up a theme if you're specifying it directly. Generally jobs execute via CLI, which may be having an effect somewhere on the line, but it shouldn't stop `SSViewer::set_theme()` (or the more correct `Config::inst()->update('SSViewer', 'theme', $theme);`)

One thing you might want to check is whether `Config::inst()->get('SSViewer', 'theme_enabled')` is returning true or not?

**Comment by diegopego86** [comment]
Same problem here, has anyone found a solution for this?

**Comment by diegopego86** [comment]
I got a way around it and it was to pass all the html body:
`$email->setBody($my_html);`

To keep my code clean I created a subclass MyCustomEmail like this:
```
class MyCustomEmail extends Email {
    public function __construct($from, $member) {
        $from = $from;
        $to = $member->Email;
        $subject = "Innactive Account";
        parent::__construct($from, $to, $subject);
        $this->setBody($this->CustomBody($member));
    }
    private function CustomBody($member){
        $data = 'My HTML goes here '.$member->Email;
        return $data;
    }
}
```
Then I call it:

```
$email = new MyCustomEmail($from, $member);
$email->send();
```
Hope this helps.

**Comment by mikeyc7m** [comment]
ooh sorry forgot about this issue. yeah the solution is to manually set the theme, like nyeholt said.
 
`Config::inst()->update('SSViewer', 'theme_enabled', true);`
`Config::inst()->update('SSViewer', 'theme', SiteConfig::current_site_config()->Theme);`

if the queuedjob is running outside of a website structure (ie. not on a page controller) it doesn't know what website theme to apply, so need to manually specify. i've referenced current_site_siteconfig, could alternatively reference `Config::inst()->get('SSViewer', 'theme')`

and yeah, it's not specific to this module.
