### ISSUE TITLE
Class SilverStripe\\QueuedJobs\\Jobs\\DoormanProcessManager may not inherit from final class (AsyncPHP\\Doorman\\Manager\\ProcessManager)

### ISSUE THREAD

**Issue by edlinklater** [symbiote/silverstripe-queuedjobs#126]
Related to the upgrade of asyncphp/doorman in #122 

`ProcessManager` was updated to be a final class in https://github.com/asyncphp/doorman/commit/58737c0a19ef5febf4a561982bfaf817240a8c2f

**Comment by robbieaverill** [comment]
@edlinklater - done in #125?

**Comment by robbieaverill** [comment]
Done in #125
