### ISSUE TITLE
"The queued jobs module must be installed in /queuedjobs, not silverstripe-queuedjobs"

### ISSUE THREAD

**Issue by spekulatius** [symbiote/silverstripe-queuedjobs#131]
Hey @nglasl 

I've updated the namespace and got this issue. Just letting you know.

Cheers,
Peter

**Comment by nglasl** [comment]
Hi @spekulatius, thanks for getting in touch! Can you please try again? I assume you're pulling down the latest ~2.X version, but I may be wrong?

**Comment by nglasl** [comment]
Sorry I should probably give a little more insight. You may need to remove the module and let composer do its thing once more. The aim is for it to actually end up on **queuedjobs** and not **silverstripe-queuedjobs** :)

**Comment by spekulatius** [comment]
I think I understand whats going on. I've changed the package name in my composer.json and ran update. Its a SS3 project and get 2.9.1....  I just saw there are 4.x tags for SS4. Do you think it makes sense to add tag 2.9.2 based off 2.9.1. with the installer-name in the composer.json?

**Comment by nglasl** [comment]
Yeah, that'll definitely be the issue. I've just created a 2.9.2 tag, please give that a try.

**Comment by spekulatius** [comment]
Awesome. Give me a sec.

**Comment by spekulatius** [comment]
I've been waiting for a little but it seems like the update doesn't get thought to packagist. Is the package configured to be updated automatically?

**Comment by nglasl** [comment]
Heh, nope, my apologies for missing that. Have forced an update, so it should be good now.

**Comment by spekulatius** [comment]
All good :)

**Comment by spekulatius** [comment]
Yupp, works and is in "queuedjobs" now. Thanks for your help fixing this :)
