### ISSUE TITLE
New Symbiote package still references abandoned multivaluefield

### ISSUE THREAD

**Issue by phptek** [symbiote/silverstripe-queuedjobs#133]
For versions  ~2.10.x composer.json stil refers to '"silverstripe/multivaluefield": "~2.0". It should be changed to "symbiote//multivaluefield": "~2.0".

**Comment by nglasl** [comment]
Thanks for getting in touch! PR #132 has now been merged through, and you should no longer be seeing this suggestion when using the 2.10 branch.
