### ISSUE TITLE
Can you loosen the requirements for silverstripe/admin please

### ISSUE THREAD

**Issue by bendubuisson** [symbiote/silverstripe-queuedjobs#137]
I'm running the latest beta2 `1.0.0-beta-2` and it complains:

```
Can only install one of: silverstripe/admin[1.0.x-dev, 1.0.0-beta2].
```

**Comment by wilr** [comment]
@nyeholt I'm keen to remove the admin component into a `silverstripe-queuedjobs-admin` module since a bunch of our projects are framework only / graphql

**Comment by dhensby** [comment]
@bendubuisson fancy opening a PR?

**Comment by bendubuisson** [comment]
https://github.com/symbiote/silverstripe-queuedjobs/pull/138
Cheers
