### ISSUE TITLE
Split Doorman into a seperate module

### ISSUE THREAD

**Issue by silbinarywolf** [symbiote/silverstripe-queuedjobs#145]
When trying to setup PHPStan on a 3.6+ project, I was unable to install PHP-Parser because Doorman via SuperClosure, locks it at ~0.8 (or something around there).

How should a major version bump be handled for 3.X modules?

**Comment by robbieaverill** [comment]
A quick note: in the SilverStripe core modules there's a "no major changes" policy in SS3 now, to avoid having this issue with semver bumping over the top of SS4 versions.

**Comment by dhensby** [comment]
> How should a major version bump be handled for 3.X modules?

that's just down to preference of the maintainers, really. There's nothing stopping you having a module where 1.x works on SS 3.x, 2.x works on SS 4.x and 3.x works on SS 3.x, it would just be a bit weird ;)

**Comment by GuySartorelli** [comment]
I think the question was answered. Given the question was "How should a major version bump be handled for 3.X modules?" this sounds like a support issue which we don't like to have around so I'm going to close this.
