### ISSUE TITLE
Ensure run as user is cleared at the end of each runJob

### ISSUE THREAD

**Issue by stephenmcm** [symbiote/silverstripe-queuedjobs#155]
Currently as the queue is processed if there's no Member with the ID of 0 the run as user won't be cleared causing the next picked up job to store this user as the original user.
If this job doesn't have a run as user set it will then execute with the run as user from the previous job.
PR to fix this in 2.x here:
https://github.com/symbiote/silverstripe-queuedjobs/pull/154

**Comment by robbieaverill** [comment]
Fixed with #154, thanks @stephenmcm
