### ISSUE TITLE
GenerateGoogleSitemapJob contains legacy code

### ISSUE THREAD

**Issue by phptek** [symbiote/silverstripe-queuedjobs#156]
PHP 7.0 / SS4.0.x / v~4.0.5 / GenerateGoogleSitemapJob.php

PHP seems to want calls to `increase_time_limit_to()` to be namespaced (Prepending a "root" backslash doesn't work..) also, the call to `getTempFolder()` should now be: `SilverStripe\Core\TempFolder::getTempFolder()`

**Comment by robbieaverill** [comment]
Cool - so `increase_time_limit_to` is now `Environment::increaseTimeLimitTo`, and you've noted the `getTempFolder` move. Fancy a PR?

**Comment by phptek** [comment]
Sure. On holiday down south with no computer, soon though :-)

**Comment by robbieaverill** [comment]
Sounds lovely
