### ISSUE TITLE
Update icon or icon colour to match other SS4 icons in the CMS

### ISSUE THREAD

**Issue by raissanorth** [symbiote/silverstripe-queuedjobs#162]
![screen shot 2018-01-26 at 9 06 47 am](https://user-images.githubusercontent.com/14869519/35410546-aa679a60-027a-11e8-8f10-9ed20d9f678b.png)
I suggest to use a font icon from core, perhaps the clipboard pencil one?
![screen shot 2018-01-26 at 9 24 18 am](https://user-images.githubusercontent.com/14869519/35410580-c4487ec2-027a-11e8-9003-2f9b31c3ff1c.png)
@sachajudd @clarkepaul

**Comment by sachajudd** [comment]
Sounds good! @raissanorth Happy with using clipboard-pencil 🙂

**Comment by dhensby** [comment]
Not to be too pedantic here, but I'm really not sure a clipboard is a good icon to use. I'm not sure where the icons come from, but I think we should be using something like a list or set of checkboxes or even a stack of items... something that indicates a list of things to be done..

A clipboard is too synonymous with copy/paste to be relevant to "jobs" IMO.

**Comment by dhensby** [comment]
Maybe this? ![drawer icon](https://dl.dropboxusercontent.com/s/z5i6s3dt0v8hxjv/2018-01-26_16-44-07_52b544a3-519e-4009-96e9-b25c64e8826f.png)

**Comment by robbieaverill** [comment]
cc @sachajudd

**Comment by NightJar** [comment]
I guess the clipboard is more to conjure up images of a checklist.
I'm not sure a drawer really covers it either.

But in any case, don't the icons now come from a font(awesome?), and are therefore reasonably limited in selection?
Or does fontastic allow this?

**Comment by raissanorth** [comment]
@clarkepaul @sachajudd what do you think?

**Comment by clarkepaul** [comment]
Fantastic allows us to add any "open sourced" font or custom designed icon. The clipboard was chosen as it was already part of the set and was to communicate a checklist. Personally I'm not too fussed as to what icon we use, but personally I don't think the icon looks like a copy-paste icon in the context it is being used (as a menu item). Icons are often going to be slightly abstract, thats why we have usually text to accompany them which should communicate a clearer message. 

I think we should stay clear of a list of items as we already use that icon for change from grid/list view for a few admin areas. Happy to add a different icon if there is any consensus for a better one.

Another option to add to the confusion :) although not sure how this one looks with the other menu icons.
![image](https://user-images.githubusercontent.com/555033/35488082-efe1f652-04e7-11e8-8e46-520ad5574265.png)

**Comment by NightJar** [comment]
I'm going to re-open this issue so we can keep track of the conversation.

**Comment by dhensby** [comment]
I like @clarkepaul's icon :)

**Comment by clarkepaul** [comment]
Cool, I get that added to the icon set today—I just need to make sure it works with the other menu icons.

**Comment by robbieaverill** [comment]
Switching to an enhancement
