### ISSUE TITLE
Consider using queue interprop as abstraction for queues

### ISSUE THREAD

**Issue by makasim** [symbiote/silverstripe-queuedjobs#165]
Hello!

Please look at https://github.com/queue-interop/queue-interop project. Using interfaces from it allows us reuse some implementations like enqueue, which supports a lot of transports. You can outsource some code

**Comment by dhensby** [comment]
Hi, thanks for this. I'm a big fan of using libraries to provide this kind of functionality for existing modules.

However, that (your?) repo is quite new (6 months old, only 3 contributors, 3 issues, 1 fork) and it'd be quite a risk to extract or rewrite the logic of this module to depend on such a young library at this time.

**Comment by makasim** [comment]
That's a project built on top of queue interop https://github.com/php-enqueue/enqueue-dev, quite popular 

despite it is young it's already caught some interest https://packagist.org/packages/queue-interop/queue-interop/stats

**Comment by dhensby** [comment]
Interesting, thanks. I'll keep this close as it's not a bug and we use the issue tracker for bugs only.

I'd be interested in adding something like this to the core framework, though

**Comment by makasim** [comment]
@dhensby don't hesitate to ask me any questions regarding this!

**Comment by dhensby** [comment]
@makasim this issue is probably more relevant: https://github.com/silverstripe/silverstripe-framework/issues/6524
