### ISSUE TITLE
Logged in user disconnected after Cron job

### ISSUE THREAD

**Issue by DrMartinGonzo** [symbiote/silverstripe-queuedjobs#166]
Each time the queuedjobs are processed, I'm no longer logged in in CMS unless I refresh the page.

This creates problem if I'm editing a page and saving, I get `Your session has expired. Please re-submit the form.`message and loses all changes.

Is this normal behavior ? If so, is there a way to avoid it ?

**Comment by dhensby** [comment]
@DrMartinGonzo what versions of SS and this module are you using?

**Comment by DrMartinGonzo** [comment]
@dhensby I use `"silverstripe/recipe-cms": "1.0.3"`which I believe loads silverstripe 4.03
and `"symbiote/silverstripe-queuedjobs": "^4.0.6"` defined by silverstripe/staticpublishqueue

**Comment by NightJar** [comment]
@DrMartinGonzo can you please tell use how these jobs are running? Is it a job you've started manually from the administrative panel, or is it just any time any job finishes running, whether or not it was started via schedule or by a user?

**Comment by NightJar** [comment]
I am having trouble replicating this issue. Can you please provide some more specific instructions on how you experience this?
For reference, I am using the development `master` HEAD at f42727318ad9eaa6fe5f7be0af2edb5f8df066ec

**Comment by NightJar** [comment]
After reviewing the thread with @chrispenny's PR at #172 (and in particular [Chris' comment](https://github.com/symbiote/silverstripe-queuedjobs/pull/172#issuecomment-373549081)) I feel certain that this has been solved.

Please feel free to re-open if the issue persists after obtaining the latest changes :)

**Comment by DrMartinGonzo** [comment]
Sorry I was away, I'm still having the same problem with latest `master`.
I'm using queuedjobs with latest silverstripe/staticpublishqueue.
Here is the problem with more detailed steps.
- User is logged in and editing a page in CMS
- Cron is running pending jobs
- User has finished editing the page, try to publish it and receives `SilverStripe\Forms\Form.CSRF_EXPIRED_MESSAGE`message. (Your session has expired) while the page gets reset 
- If he refreshes the page or try to publish again, it will work, but all previous changes have been lost.

I'll try with ContentReviewNotificationJob when I get time to see if the problem is specific to staticpublishqueue.

**Comment by chrispenny** [comment]
That does sound unrelated to the issue that I solved. What I solved was really only related to when a user runs the Queue manually via `/dev/tasks/ProcessJobQueueTask`, not when it's run through a cron.

I have tried the following steps, but I haven't been able to replicate your experience.

**Main browser session**
1. Log in to CMS
2. Edit a Page (don't save)

**Incognito session**
1. Queue some Jobs
2. Confirm that the Jobs have started and completed via cron

**Main browser session**
1. Hit "Save & publish"
2. Publish was successful

I followed these steps in a local Vagrant environment, and in a SS Platform environment.

**Comment by NightJar** [comment]
@DrMartinGonzo In the example you've given, how long is it between the user loading the page to edit, and clicking the save button?

**Comment by dhensby** [comment]
It's bizarre that you can reload the page and it doesn't ask for re-authentication. This indicates that the security token has been expired somehow but your actual session has stayed in tact.

Do you have any custom code around `SecurityToken` that could be forcing your `SecurityToken` to be regenerated?
