### ISSUE TITLE
v4: User not correctly set on Job processing?

### ISSUE THREAD

**Issue by chrispenny** [symbiote/silverstripe-queuedjobs#168]
Potentially also relates to issue https://github.com/symbiote/silverstripe-queuedjobs/issues/166.

## Issue

The `$runAsUser` record is valid, and is being found (and set) by `QueuedJobService::runJob()`, but then that user is not available from within the `Job`.

## Trace

The essence of my Debug (in order):

`QueuedJobService`:
**Line 607**: `if ($runAsUser && $runAsUser->exists())` returned `true`.
**Line 610**: `if (Controller::has_curr())` returned `true`.
**Line 611**: `$runAsUser` is set to session value `loggedInAs`.

`MyJob extends AbstractQueuedJob implements QueuedJob`:
**First line of`process()` method**: `Debug::dump(Security::getCurrentUser())` returned `null`.

## Minor testing

From `QueuedJobService::runJob()`, if instead of using:
`Controller::curr()->getRequest()->getSession()->set('loggedInAs', $runAsUser->ID);`
I use:
`Security::setCurrentUser($runAsUser)`
Things **appear** to work as expected.

This solution appeared to work in all instances in my own project. Unfortunately I don't have a tonne of time available to investigate what other consequences this change could have for others.

If this seems right to everyone, I'd be happy to raise a PR for it "as is".

**Comment by dhensby** [comment]
I think that fix is right - grabbing the current controller's session and messing with it seems incorrect - that's not really how it should work because the current controller won't be the controller that should provide context to the current job...

**Comment by chrispenny** [comment]
Awesome. Thanks a lot, Dan. I'll add this to my hackday list.
