### ISSUE TITLE
Inonsistent PublishItemsJob API

### ISSUE THREAD

**Issue by phptek** [symbiote/silverstripe-queuedjobs#173]
An instance of `Symbiote\QueuedJobs\Jobs\PublishItemsJob` can be instantiated with an optional `$rootNodeID`. But; the `getTitle()` method can still be called which is expecting `getRoot()` to return a `DataObject`, which it can't do if `$this->rootID` is null becuase no `$rootNodeID` is passed in construction.

The relevant part of the stack-trace where I have seen this in a SilverStripe 4 setup is as follows:

```
ORM/DataObject.php in get_by_id at line 3187
vendor/symbiote/silverstripe-queuedjobs/src/Jobs/PublishItemsJob.php in getRoot at line 34
vendor/symbiote/silverstripe-queuedjobs/src/Jobs/PublishItemsJob.php in getTitle at line 47
vendor/symbiote/silverstripe-queuedjobs/src/Services/QueuedJobService.php in queueJob at line 177
vendor/symbiote/silverstripe-queuedjobs/src/Controllers/QueuedJobsAdmin.php in createjob at line 190
```

This is just a bug-report for now. If I come up with a fix or suggestion, I'll of course update the ticket.

**Comment by robbieaverill** [comment]
Fixed with #185
