### ISSUE TITLE
DoormanRunner suppresses ProcessManager errors

### ISSUE THREAD

**Issue by frankmullenger** [symbiote/silverstripe-queuedjobs#177]
Currently cannot set the log path for the ProcessManager:
https://github.com/symbiote/silverstripe-queuedjobs/blob/master/src/Tasks/Engines/DoormanRunner.php#L53

The result is that errors thrown when exec runs the ProcessJobQueueChildTask go to /dev/null.

Preferably the log path can be set for the ProcessManager instance per project, perhaps a hook with the instance passed as an argument is the easiest option.

**Comment by robbieaverill** [comment]
We could implement a backwards compatible change here where the log path could be configurable and null by default. How does that sound?

**Comment by frankmullenger** [comment]
@robbieaverill that would be great thanks, we would ideally like to set the log path on a per project and per environment basis.

**Comment by robbieaverill** [comment]
@frankmullenger sweet, how does the PR at #178 look?

**Comment by frankmullenger** [comment]
Looks good to me, cheers!
