### ISSUE TITLE
intldateformatter::format(): error converting value to utf-8

### ISSUE THREAD

**Issue by DorsetDigital** [symbiote/silverstripe-queuedjobs#199]
I've been seeing an odd behaviour with a site I've just been trying to deploy to a production server.

The error in the title was thrown every time I tried to run the `ProcessJobQueueTask` task.

Digging into it a bit more, the traced pointed to line 910 of `QueuedJobService` where the start time is calculated:  `DBDatetime::now()->Format('U');`

This line (and line 931 in the same file) appear to use the PHP `date()` format for the timestamp (an uppercase 'U').  

Looking at `DBDate::format()`, the docblock suggests that the format should be passed in using the format specified here:  http://userguide.icu-project.org/formatparse/datetime     
On that page, an uppercase 'U' is a "cyclic year name, as in Chinese lunar calendar", which may explain why I'm getting a warning about UTF.

Changing lines 910 & 935 in the `QueuedJobService` class to use `DBDateTime::now()->getTimestamp()` seems to fix the issue.

What I'm not 100% sure of is whether the above is the actual root cause, or whether I'm just fixing the symptom.  The task runs correctly on my local dev machine, so I'm wondering if this could be something else.

I'd be interested in hearing any views before I start proposing changes!

**Comment by DorsetDigital** [comment]
Apologies, my software versions in case it helps:

silverstripe/admin                             1.1.1              
silverstripe/asset-admin                       1.1.1              
silverstripe/assets                            1.1.1              
silverstripe/blog                              3.2.0              
silverstripe/campaign-admin                    1.1.1              
silverstripe/cms                               4.1.1  
silverstripe/config                            1.0.4       
silverstripe/errorpage                         1.1.1        
silverstripe/framework                         4.1.1             
silverstripe/graphql                           1.1.1           
silverstripe/lumberjack                        2.0.0          
silverstripe/recipe-cms                        1.1.1            
silverstripe/recipe-core                       1.1.1            
silverstripe/recipe-plugin                     1.3.0             
silverstripe/reports                           4.1.1             
silverstripe/siteconfig                        4.1.1             
silverstripe/staticpublishqueue                4.0.0-beta.1      
silverstripe/tagfield                          2.1.0        
silverstripe/vendor-plugin                     1.3.3             
silverstripe/versioned                         1.1.1             
swiftmailer/swiftmailer                        v5.4.9            
symbiote/silverstripe-multivaluefield          5.0.1              
symbiote/silverstripe-queuedjobs               4.2.2

**Comment by tractorcow** [comment]
ProcessJobQueueTask is using the wrong date string. `U` is the old php datetime format. It should use getTimestamp() internally.

**Comment by robbieaverill** [comment]
Thanks for the patch @DorsetDigital. I'll cherry-pick this commit back into 4.2 so it can be released soon, then close this issue.
