### ISSUE TITLE
Process Job Queue Task - not working and giving long error 

### ISSUE THREAD

**Issue by spark-green** [symbiote/silverstripe-queuedjobs#202]
ERROR [Emergency]: **Uncaught Error: Call to a member function clearOwner() on null IN POST /admin/queuedjobs/Symbiote-QueuedJobs-DataObjects-QueuedJobDescriptor/EditForm/field/QueuedJobDescriptor Line 146 in /var/www/project/directory/vendor/silverstripe/framework/src/Core/Extensible.php Source** ====== 137: foreach ($extensions as $extensionClass => $extensionInstance) { 138: foreach ($this->findMethodsFromExtension($extensionInstance) as $method) { 139: $this->addCallbackMethod($method, function ($inst, $args) use ($method, $extensionClass) { 140: /** @var Extensible $inst */ 141: $extension = $inst->getExtensionInstance($extensionClass); 142: try { 143: $extension->setOwner($inst); 144: return call_user_func_array([$extension, $method], $args); 145: } finally { * 146: $extension->clearOwner(); 147: } 148: }); 149: } 150: } 151: } 152: Trace ===== SilverStripe\View\ViewableData->SilverStripe\Core\{closure}(HomePage, Array) CustomMethods.php:61 SilverStripe\View\ViewableData->__call(getHomePageCarousele, Array) CustomMethods.php:79 SilverStripe\View\ViewableData->__call(getHomePageCarousele, Array) call_user_func_array(Array, Array) ViewableData.php:481 SilverStripe\View\ViewableData->obj(getHomePageCarousele, , 1, getHomePageCarousele) SSViewer_Scope.php:179 SilverStripe\View\SSViewer_Scope->getObj(getHomePageCarousele, , 1, ) SSViewer_DataPresenter.php:282 SilverStripe\View\SSViewer_DataPresenter->getObj(getHomePageCarousele, , 1, ) SSViewer_Scope.php:217 SilverStripe\View\SSViewer_Scope->obj(getHomePageCarousele, , 1, ) SSViewer_DataPresenter.php:269 SilverStripe\View\SSViewer_DataPresenter->obj(getHomePageCarousele, , 1) .cachethemes.milliman.templates.Layout.HomePage.ss:22 include(/tmp/silverstripe-cache-php7.0.31-1+ubuntu16.04.1+deb.sury.org+1-var-www-milliman-githtdocs/www-data/.cachethemes.milliman.templates.Layout.HomePage.ss) SSViewer.php:602 SilverStripe\View\SSViewer->includeGeneratedTemplate(/tmp/silverstripe-cache-php7.0.31-1+ubuntu16.04.1+deb.sury.org+1-var-www-milliman-githtdocs/www-data/.cachethemes.milliman.templates.Layout.HomePage.ss, HomePageController, , Array, ) SSViewer.php:674 SilverStripe\View\SSViewer->process(HomePageController, ) SSViewer.php:668 SilverStripe\View\SSViewer->SilverStripe\View\{closure}() SSViewer_DataPresenter.php:330 SilverStripe\View\SSViewer_DataPresenter->processTemplateOverride(Layout, Array) SSViewer_DataPresenter.php:363 SilverStripe\View\SSViewer_DataPresenter->getValueSource(Layout) SSViewer_DataPresenter.php:165 SilverStripe\View\SSViewer_DataPresenter->getInjectedValue(Layout, Array) SSViewer_DataPresenter.php:296 SilverStripe\View\SSViewer_DataPresenter->__call(XML_val, Array) .cachethemes.milliman.templates.Page.ss:71 include(/tmp/silverstripe-cache-php7.0.31-1+ubuntu16.04.1+deb.sury.org+1-var-www-milliman-githtdocs/www-data/.cachethemes.milliman.templates.Page.ss) SSViewer.php:602 SilverStripe\View\SSViewer->includeGeneratedTemplate(/tmp/silverstripe-cache-php7.0.31-1+ubuntu16.04.1+deb.sury.org+1-var-www-milliman-githtdocs/www-data/.cachethemes.milliman.templates.Page.ss, HomePageController, , Array, ) SSViewer.php:674 SilverStripe\View\SSViewer->process(HomePageController) Controller.php:303 SilverStripe\Control\Controller->handleAction(SilverStripe\Control\HTTPRequest, index) RequestHandler.php:201 SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest) Controller.php:212 SilverStripe\Control\Controller->handleRequest(SilverStripe\Control\HTTPRequest) ContentController.php:237 SilverStripe\CMS\Controllers\ContentController->handleRequest(SilverStripe\Control\HTTPRequest) ModelAsController.php:100 SilverStripe\CMS\Controllers\ModelAsController->handleRequest(SilverStripe\Control\HTTPRequest) RootURLController.php:142 SilverStripe\CMS\Controllers\RootURLController->handleRequest(SilverStripe\Control\HTTPRequest) Director.php:361 SilverStripe\Control\Director->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) VersionedHTTPMiddleware.php:40 SilverStripe\Versioned\VersionedHTTPMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) BasicAuthMiddleware.php:68 SilverStripe\Security\BasicAuthMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) AuthenticationMiddleware.php:61 SilverStripe\Security\AuthenticationMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) CanonicalURLMiddleware.php:156 SilverStripe\Control\Middleware\CanonicalURLMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) FlushMiddleware.php:26 SilverStripe\Control\Middleware\FlushMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) RequestProcessor.php:66 SilverStripe\Control\RequestProcessor->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) SessionMiddleware.php:20 SilverStripe\Control\Middleware\SessionMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) AllowedHostsMiddleware.php:60 SilverStripe\Control\Middleware\AllowedHostsMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) TrustedProxyMiddleware.php:176 SilverStripe\Control\Middleware\TrustedProxyMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) HTTPMiddlewareAware.php:65 SilverStripe\Control\Director->callMiddleware(SilverStripe\Control\HTTPRequest, Closure) Director.php:370 SilverStripe\Control\Director->handleRequest(SilverStripe\Control\HTTPRequest) HTTPApplication.php:48 SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) call_user_func(Closure, SilverStripe\Control\HTTPRequest) HTTPApplication.php:66 SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) HTTPMiddlewareAware.php:65 SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest, Closure) HTTPApplication.php:67 SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest, Closure, ) HTTPApplication.php:49 SilverStripe\Control\HTTPApplication->handle(SilverStripe\Control\HTTPRequest) Publisher.php:94 SilverStripe\StaticPublishQueue\Publisher->generatePageResponse(https://milliman.sparkgreen.com.au/) FilesystemPublisher.php:97 SilverStripe\StaticPublishQueue\Publisher\FilesystemPublisher->publishURL(https://milliman.sparkgreen.com.au/, 1) StaticCacheFullBuildJob.php:54 SilverStripe\StaticPublishQueue\Job\StaticCacheFullBuildJob->process() QueuedJobService.php:710 Symbiote\QueuedJobs\Services\QueuedJobService->runJob(43) QueuedJobDescriptor.php:225 Symbiote\QueuedJobs\DataObjects\QueuedJobDescriptor->execute() GridFieldQueuedJobExecute.php:169 Symbiote\QueuedJobs\Forms\GridFieldQueuedJobExecute->handleAction(SilverStripe\Forms\GridField\GridField, execute, Array, Array) GridField.php:965 SilverStripe\Forms\GridField\GridField->handleAlterAction(execute, Array, Array) GridField.php:930 SilverStripe\Forms\GridField\GridField->gridFieldAlterAction(Array, SilverStripe\Forms\Form, SilverStripe\Control\HTTPRequest) GridField.php:147 SilverStripe\Forms\GridField\GridField->index(SilverStripe\Control\HTTPRequest) RequestHandler.php:319 SilverStripe\Control\RequestHandler->handleAction(SilverStripe\Control\HTTPRequest, index) RequestHandler.php:201 SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest) GridField.php:1075 SilverStripe\Forms\GridField\GridField->handleRequest(SilverStripe\Control\HTTPRequest) RequestHandler.php:225 SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest) RequestHandler.php:225 SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest) Controller.php:212 SilverStripe\Control\Controller->handleRequest(SilverStripe\Control\HTTPRequest) LeftAndMain.php:752 SilverStripe\Admin\LeftAndMain->handleRequest(SilverStripe\Control\HTTPRequest) AdminRootController.php:123 SilverStripe\Admin\AdminRootController->handleRequest(SilverStripe\Control\HTTPRequest) Director.php:361 SilverStripe\Control\Director->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) VersionedHTTPMiddleware.php:40 SilverStripe\Versioned\VersionedHTTPMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) BasicAuthMiddleware.php:68 SilverStripe\Security\BasicAuthMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) AuthenticationMiddleware.php:61 SilverStripe\Security\AuthenticationMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) CanonicalURLMiddleware.php:156 SilverStripe\Control\Middleware\CanonicalURLMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) FlushMiddleware.php:26 SilverStripe\Control\Middleware\FlushMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) RequestProcessor.php:66 SilverStripe\Control\RequestProcessor->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) SessionMiddleware.php:20 SilverStripe\Control\Middleware\SessionMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) AllowedHostsMiddleware.php:60 SilverStripe\Control\Middleware\AllowedHostsMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) TrustedProxyMiddleware.php:176 SilverStripe\Control\Middleware\TrustedProxyMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) HTTPMiddlewareAware.php:65 SilverStripe\Control\Director->callMiddleware(SilverStripe\Control\HTTPRequest, Closure) Director.php:370 SilverStripe\Control\Director->handleRequest(SilverStripe\Control\HTTPRequest) HTTPApplication.php:48 SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) call_user_func(Closure, SilverStripe\Control\HTTPRequest) HTTPApplication.php:66 SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) call_user_func(Closure, SilverStripe\Control\HTTPRequest) ErrorControlChainMiddleware.php:56 SilverStripe\Core\Startup\ErrorControlChainMiddleware->SilverStripe\Core\Startup\{closure}(SilverStripe\Core\Startup\ErrorControlChain) call_user_func(Closure, SilverStripe\Core\Startup\ErrorControlChain) ErrorControlChain.php:236 SilverStripe\Core\Startup\ErrorControlChain->step() ErrorControlChain.php:226 SilverStripe\Core\Startup\ErrorControlChain->execute() ErrorControlChainMiddleware.php:69 SilverStripe\Core\Startup\ErrorControlChainMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\HTTPApplication->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) HTTPMiddlewareAware.php:65 SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest, Closure) HTTPApplication.php:67 SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest, Closure, ) HTTPApplication.php:49 SilverStripe\Control\HTTPApplication->handle(SilverStripe\Control\HTTPRequest) index.php:26 ERROR [Emergency]: Uncaught Error: Call to a member function clearOwner() on null IN POST /admin/queuedjobs/Symbiote-QueuedJobs-DataObjects-QueuedJobDescriptor/EditForm/field/QueuedJobDescriptor Line 146 in /var/www/project/directory/vendor/silverstripe/framework/src/Core/Extensible.php Source ====== 137: foreach ($extensions as $extensionClass => $extensionInstance) { 138: foreach ($this->findMethodsFromExtension($extensionInstance) as $method) { 139: $this->addCallbackMethod($method, function ($inst, $args) use ($method, $extensionClass) { 140: /** @var Extensible $inst */ 141: $extension = $inst->getExtensionInstance($extensionClass); 142: try { 143: $extension->setOwner($inst); 144: return call_user_func_array([$extension, $method], $args); 145: } finally { * 146: $extension->clearOwner(); 147: } 148: }); 149: } 150: } 151: } 152: Trace ===== SilverStripe\View\ViewableData->SilverStripe\Core\{closure}(HomePage, Array) CustomMethods.php:61 SilverStripe\View\ViewableData->__call(getHomePageCarousele, Array) CustomMethods.php:79 SilverStripe\View\ViewableData->__call(getHomePageCarousele, Array) call_user_func_array(Array, Array) ViewableData.php:481 SilverStripe\View\ViewableData->obj(getHomePageCarousele, , 1, getHomePageCarousele) SSViewer_Scope.php:179 SilverStripe\View\SSViewer_Scope->getObj(getHomePageCarousele, , 1, ) SSViewer_DataPresenter.php:282 SilverStripe\View\SSViewer_DataPresenter->getObj(getHomePageCarousele, , 1, ) SSViewer_Scope.php:217 SilverStripe\View\SSViewer_Scope->obj(getHomePageCarousele, , 1, ) SSViewer_DataPresenter.php:269 SilverStripe\View\SSViewer_DataPresenter->obj(getHomePageCarousele, , 1) .cachethemes.milliman.templates.Layout.HomePage.ss:22 include(/tmp/silverstripe-cache-php7.0.31-1+ubuntu16.04.1+deb.sury.org+1-var-www-milliman-githtdocs/www-data/.cachethemes.milliman.templates.Layout.HomePage.ss) SSViewer.php:602 SilverStripe\View\SSViewer->includeGeneratedTemplate(/tmp/silverstripe-cache-php7.0.31-1+ubuntu16.04.1+deb.sury.org+1-var-www-milliman-githtdocs/www-data/.cachethemes.milliman.templates.Layout.HomePage.ss, HomePageController, , Array, ) SSViewer.php:674 SilverStripe\View\SSViewer->process(HomePageController, ) SSViewer.php:668 SilverStripe\View\SSViewer->SilverStripe\View\{closure}() SSViewer_DataPresenter.php:330 SilverStripe\View\SSViewer_DataPresenter->processTemplateOverride(Layout, Array) SSViewer_DataPresenter.php:363 SilverStripe\View\SSViewer_DataPresenter->getValueSource(Layout) SSViewer_DataPresenter.php:165 SilverStripe\View\SSViewer_DataPresenter->getInjectedValue(Layout, Array) SSViewer_DataPresenter.php:296 SilverStripe\View\SSViewer_DataPresenter->__call(XML_val, Array) .cachethemes.milliman.templates.Page.ss:71 include(/tmp/silverstripe-cache-php7.0.31-1+ubuntu16.04.1+deb.sury.org+1-var-www-milliman-githtdocs/www-data/.cachethemes.milliman.templates.Page.ss) SSViewer.php:602 SilverStripe\View\SSViewer->includeGeneratedTemplate(/tmp/silverstripe-cache-php7.0.31-1+ubuntu16.04.1+deb.sury.org+1-var-www-milliman-githtdocs/www-data/.cachethemes.milliman.templates.Page.ss, HomePageController, , Array, ) SSViewer.php:674 SilverStripe\View\SSViewer->process(HomePageController) Controller.php:303 SilverStripe\Control\Controller->handleAction(SilverStripe\Control\HTTPRequest, index) RequestHandler.php:201 SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest) Controller.php:212 SilverStripe\Control\Controller->handleRequest(SilverStripe\Control\HTTPRequest) ContentController.php:237 SilverStripe\CMS\Controllers\ContentController->handleRequest(SilverStripe\Control\HTTPRequest) ModelAsController.php:100 SilverStripe\CMS\Controllers\ModelAsController->handleRequest(SilverStripe\Control\HTTPRequest) RootURLController.php:142 SilverStripe\CMS\Controllers\RootURLController->handleRequest(SilverStripe\Control\HTTPRequest) Director.php:361 SilverStripe\Control\Director->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) VersionedHTTPMiddleware.php:40 SilverStripe\Versioned\VersionedHTTPMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) BasicAuthMiddleware.php:68 SilverStripe\Security\BasicAuthMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) AuthenticationMiddleware.php:61 SilverStripe\Security\AuthenticationMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) CanonicalURLMiddleware.php:156 SilverStripe\Control\Middleware\CanonicalURLMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) FlushMiddleware.php:26 SilverStripe\Control\Middleware\FlushMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) RequestProcessor.php:66 SilverStripe\Control\RequestProcessor->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) SessionMiddleware.php:20 SilverStripe\Control\Middleware\SessionMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) AllowedHostsMiddleware.php:60 SilverStripe\Control\Middleware\AllowedHostsMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) TrustedProxyMiddleware.php:176 SilverStripe\Control\Middleware\TrustedProxyMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) HTTPMiddlewareAware.php:65 SilverStripe\Control\Director->callMiddleware(SilverStripe\Control\HTTPRequest, Closure) Director.php:370 SilverStripe\Control\Director->handleRequest(SilverStripe\Control\HTTPRequest) HTTPApplication.php:48 SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) call_user_func(Closure, SilverStripe\Control\HTTPRequest) HTTPApplication.php:66 SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) HTTPMiddlewareAware.php:65 SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest, Closure) HTTPApplication.php:67 SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest, Closure, ) HTTPApplication.php:49 SilverStripe\Control\HTTPApplication->handle(SilverStripe\Control\HTTPRequest) Publisher.php:94 SilverStripe\StaticPublishQueue\Publisher->generatePageResponse(https://milliman.sparkgreen.com.au/) FilesystemPublisher.php:97 SilverStripe\StaticPublishQueue\Publisher\FilesystemPublisher->publishURL(https://milliman.sparkgreen.com.au/, 1) StaticCacheFullBuildJob.php:54 SilverStripe\StaticPublishQueue\Job\StaticCacheFullBuildJob->process() QueuedJobService.php:710 Symbiote\QueuedJobs\Services\QueuedJobService->runJob(43) QueuedJobDescriptor.php:225 Symbiote\QueuedJobs\DataObjects\QueuedJobDescriptor->execute() GridFieldQueuedJobExecute.php:169 Symbiote\QueuedJobs\Forms\GridFieldQueuedJobExecute->handleAction(SilverStripe\Forms\GridField\GridField, execute, Array, Array) GridField.php:965 SilverStripe\Forms\GridField\GridField->handleAlterAction(execute, Array, Array) GridField.php:930 SilverStripe\Forms\GridField\GridField->gridFieldAlterAction(Array, SilverStripe\Forms\Form, SilverStripe\Control\HTTPRequest) GridField.php:147 SilverStripe\Forms\GridField\GridField->index(SilverStripe\Control\HTTPRequest) RequestHandler.php:319 SilverStripe\Control\RequestHandler->handleAction(SilverStripe\Control\HTTPRequest, index) RequestHandler.php:201 SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest) GridField.php:1075 SilverStripe\Forms\GridField\GridField->handleRequest(SilverStripe\Control\HTTPRequest) RequestHandler.php:225 SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest) RequestHandler.php:225 SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest) Controller.php:212 SilverStripe\Control\Controller->handleRequest(SilverStripe\Control\HTTPRequest) LeftAndMain.php:752 SilverStripe\Admin\LeftAndMain->handleRequest(SilverStripe\Control\HTTPRequest) AdminRootController.php:123 SilverStripe\Admin\AdminRootController->handleRequest(SilverStripe\Control\HTTPRequest) Director.php:361 SilverStripe\Control\Director->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) VersionedHTTPMiddleware.php:40 SilverStripe\Versioned\VersionedHTTPMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) BasicAuthMiddleware.php:68 SilverStripe\Security\BasicAuthMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) AuthenticationMiddleware.php:61 SilverStripe\Security\AuthenticationMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) CanonicalURLMiddleware.php:156 SilverStripe\Control\Middleware\CanonicalURLMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) FlushMiddleware.php:26 SilverStripe\Control\Middleware\FlushMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) RequestProcessor.php:66 SilverStripe\Control\RequestProcessor->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) SessionMiddleware.php:20 SilverStripe\Control\Middleware\SessionMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) AllowedHostsMiddleware.php:60 SilverStripe\Control\Middleware\AllowedHostsMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) TrustedProxyMiddleware.php:176 SilverStripe\Control\Middleware\TrustedProxyMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) HTTPMiddlewareAware.php:65 SilverStripe\Control\Director->callMiddleware(SilverStripe\Control\HTTPRequest, Closure) Director.php:370 SilverStripe\Control\Director->handleRequest(SilverStripe\Control\HTTPRequest) HTTPApplication.php:48 SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) call_user_func(Closure, SilverStripe\Control\HTTPRequest) HTTPApplication.php:66 SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) call_user_func(Closure, SilverStripe\Control\HTTPRequest) ErrorControlChainMiddleware.php:56 SilverStripe\Core\Startup\ErrorControlChainMiddleware->SilverStripe\Core\Startup\{closure}(SilverStripe\Core\Startup\ErrorControlChain) call_user_func(Closure, SilverStripe\Core\Startup\ErrorControlChain) ErrorControlChain.php:236 SilverStripe\Core\Startup\ErrorControlChain->step() ErrorControlChain.php:226 SilverStripe\Core\Startup\ErrorControlChain->execute() ErrorControlChainMiddleware.php:69 SilverStripe\Core\Startup\ErrorControlChainMiddleware->process(SilverStripe\Control\HTTPRequest, Closure) HTTPMiddlewareAware.php:62 SilverStripe\Control\HTTPApplication->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest) HTTPMiddlewareAware.php:65 SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest, Closure) HTTPApplication.php:67 SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest, Closure, ) HTTPApplication.php:49 SilverStripe\Control\HTTPApplication->handle(SilverStripe\Control\HTTPRequest) index.php:26

**Comment by robbieaverill** [comment]
Hi there, thank you for raising this issue. Please provide some steps to reproduce the problem and information about the environment, e.g. which modules you have installed and which versions they are.

**Comment by spark-green** [comment]
Hi @robbieaverill 

Much appreciate your quick reply,

I am using below modules 

>         "php": ">=5.6.0",
>         "silverstripe/cms": "4.1.2",
>         "silverstripe/framework": "4.1.2",
>         "silverstripe/recipe-plugin": "^1",
>         "silverstripe/recipe-cms": "1.*",
>         "silverstripe/versioned": "1.*",
>         "silverstripe/blog": "3.*",
>         "silverstripe/widgets": "2.*",
>         "ryanpotter/silverstripe-cms-theme": "2.*",
>         "undefinedoffset/sortablegridfield": "2.*",
>         "silverstripe/staticpublishqueue": "4.*",
>         "jonom/focuspoint": "dev-master",
>         "unclecheese/display-logic": "2.*",
>         "sheadawson/silverstripe-linkable": "2.*",
>         "silverware/validator": "1.*",
>         "jonom/silverstripe-text-target-length": "2.*",
>         "axllent/silverstripe-cms-tweaks": "2.*",
>         "symbiote/silverstripe-gridfieldextensions": "^3.0",
>         "tpyo/amazon-s3-php-class": "*"

After development of my project, i wanted to generate a static cache, followed below steps and got the error

Step 1 : ran command **/dev/tasks/queue/SilverStripe-StaticPublishQueue-Task-StaticCacheFullBuildTask**
            This added a task to generate static cache from URL in job queue. 

Step 2: ran command **/dev/tasks/ProcessJobQueueTask**
            Ran this command to process the task present in job queue and it gave me this error. 
             I ran this command from browser as well as from cli and i got the above error.

**Comment by robbieaverill** [comment]
@spark-green thanks, I notice your constraints are different between the framework and cms and versioned etc - could you also share your `composer show` output?
