### ISSUE TITLE
[Emergency] Uncaught Exception: Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by sparkcom** [symbiote/silverstripe-queuedjobs#203]
I have the following problem when I tried to unpublish and archive a page. I have SS4.2 and the Heyday\Elastica module installed. I think we shall use the jeremeamia/SuperClosure for searlizing 

```
===========Error message==========

[Emergency] Uncaught Exception: Serialization of 'Closure' is not allowed

POST /admin/pages/edit/EditForm/32/

Line 94 in /home/user/public_html/vendor/symbiote/silverstripe-queuedjobs/src/Services/AbstractQueuedJob.php

Source

85     }86 87     /**88      * Return a signature for this queued job89      *90      * @return string91      */92     public function getSignature()93     {94         return md5(get_class($this) . serialize($this->jobData));95     }96 97     /**98      * Generate a somewhat random signature99      *100      * useful if you're want to make sure something is always added
Trace

serialize(stdClass)
AbstractQueuedJob.php:94
Symbiote\QueuedJobs\Services\AbstractQueuedJob->getSignature()
QueuedJobService.php:162
Symbiote\QueuedJobs\Services\QueuedJobService->queueJob(Heyday\Elastica\Jobs\ReindexAfterWriteJob)
Searchable.php:457
Heyday\Elastica\Searchable->onBeforeDelete(, , , , , , )
Extensible.php:464
SilverStripe\View\ViewableData->extend(onBeforeDelete, )
DataObject.php:1234
SilverStripe\ORM\DataObject->onBeforeDelete()
SiteTree.php:1528
```

**Comment by robbieaverill** [comment]
Ok so it sounds like the Elastica module's `ReindexAfterWriteJob` returns a closure for its `jobData`. I had a quick look and I can't see where this would be happening. Perhaps you could debug AbstractQueuedJob line 94 and backtrace to see where jobData comes from when `is_callable($this->jobData)` is true?

Side note: that module instances a `ReindexAfterWriteJob` in four places, but incorrectly passes the [first ID argument](https://github.com/heyday/silverstripe-elastica/blob/master/src/Jobs/ReindexAfterWriteJob.php#L28-L32) as the owner class in three of them - example: https://github.com/heyday/silverstripe-elastica/blob/master/src/Searchable.php#L456. This should be `$reindex = new ReindexAfterWriteJob($this->owner->ID, get_class($this->owner));` in my estimation (the job constructor's PHPDoc describes the types as null, but I suspect it should be `int $id` and `string $class`).

I'd suggest reopening this issue on the https://github.com/heyday/silverstripe-elastica module to follow up further. Thanks for raising the issue though =)
