### ISSUE TITLE
Having multiple runners will check job health too often

### ISSUE THREAD

**Issue by ScopeyNZ** [symbiote/silverstripe-queuedjobs#213]
A job is considered broken if there have not been any "steps" completed since the last health check. This logic appears sound, but relies heavily on having a reasonable time period between health checks. 

Currently the health check is done when a runner starts running a queue. This is inherently flawed in a multi-worker environment, as 2 workers starting the same queue at the same time will immediately note all jobs are "stalled" - the first worker is happy, the second will think they're all stalled.

There are three potential fixes I can see
- Nominate workers that can perform health checks
- Move health checking to a separate cron - via a config setting
- Keep track of the last time a "health-check" was run and have a configurable time-period where another check is not performed

@frankmullenger What do you think would work best?

### PR:

#214

**Comment by ScopeyNZ** [comment]
I think I'll work on a PR for option 2. It can be completely non-breaking.

I think option 1 (_Nominate workers that can perform health checks_) would be too complex in implementation and configuration

Option 3 (_Keep track of the last time a "health-check" was run_) would involve a new DataObject

**Comment by robbieaverill** [comment]
I like option 2 and 3
