### ISSUE TITLE
Undefined property: SearchUpdateQueuedJobProcessor::$SubsiteID

### ISSUE THREAD

**Issue by Leapfrognz** [symbiote/silverstripe-queuedjobs#238]
```
NOTICE: Undefined property: SearchUpdateQueuedJobProcessor::$SubsiteID (line 569 in /sites/not-telling/releases/not-telling/queuedjobs/code/services/QueuedJobService.php) []
```
ie `if (isset($job->SubsiteID) && class_exists('Subsite'))` is failing.
This is on a main site not a subsite, PHP 7.1, SS 3.7.3
Simple fix, do you want me to submit a PR or can you handle it?

**Comment by robbieaverill** [comment]
We should flip the conditions the other way around. Would you like to make a PR for this?

**Comment by Leapfrognz** [comment]
https://github.com/symbiote/silverstripe-queuedjobs/pull/239

**Comment by robbieaverill** [comment]
Thanks @Leapfrognz!
