### ISSUE TITLE
Prevent stalled job email spam

### ISSUE THREAD

**Issue by IgorNadj** [symbiote/silverstripe-queuedjobs#24]
If the cron for queued jobs runs every minute, this means am email is sent every minute. It would be nice to only send an email e.g. once every hour. Especially if it's for the same stalled job.

Thanks!

**Comment by kinglozzer** [comment]
5 years later and this is still an issue 🤣perhaps we could make this optional:

https://github.com/symbiote/silverstripe-queuedjobs/blob/50b962c27f61ad76d07465c799df98704305480a/src/Services/QueuedJobService.php#L450-L453

```php
if ($this->config()->notify_broken_jobs) {
    $brokenJobs = QueuedJobDescriptor::get()->filter('JobStatus', QueuedJob::STATUS_BROKEN);
    if ($brokenJobs && $brokenJobs->count()) {
```

**Comment by phptek** [comment]
We have a similar issue, but not from email - from a bug aggregation service e.g. Sentry / RayGun. If a job legitimately throws an `Exception` in the case of an 3rd party API connection failure for example, then the module continues to attempt to run that job each time encountering the same problem, until the API is back up again.

Idea: A new method `QueuedJob::healthCheck() : bool` which is consulted by `QueuedJobService` _before_ each job is run. The job only runs if `healthCheck()` returns boolean `true`.

By default, the module always returns `true`, but the key here is that developers are able to write any logic they require on a custom job by job basis.

In our example, we could modify our job with a `healthCheck()` that simply pings the API to ensure we get a 200, before the job's logic is ever invoked.

**Comment by dnsl48** [comment]
I'm not quite sure we need to extend QueuedJobs APIs. I believe the problem can be solved with a Monolog handler.

E.g. [DeduplicationHandler](https://github.com/Seldaek/monolog/blob/master/doc/02-handlers-formatters-processors.md) could be an example of such an approach.

**Comment by lozcalver** [comment]
@dnsl48 Looks like `DeduplicationHandler` will only prevent duplicates within the current request/process, whereas we’re experiencing an email every X minutes (however often the crontab runs) - each caused by a new PHP process.

**Comment by IgorNadj** [comment]
Might be better to move the notification logic out into its own thing, that can batch and be configured for how and how often it notifies. E.g. once an hour send a "There are 35 stalled jobs" email.

**Comment by dnsl48** [comment]
@kinglozzer I'm pretty sure it can [persist](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/DeduplicationHandler.php#L171) the data in a store so that it works across multiple requests. The original implementation keeps data on the filesystem, but I guess it can be extended to use a database for that.

@IgorNadj what would be different from a monolog handler in that case?

**Comment by lozcalver** [comment]
@dnsl48 My bad, you’re right! That would definitely help here. I’m not sure what value we’d set the timeout to, maybe 1 hour + make it configurable? That default would make the notifications manageable at least.

I’ll try to find time to work on this soon

**Comment by chillu** [comment]
There's a `NotifiedBroken` flag on each job database record now, which gets checked before a message about broken jobs is logged: https://github.com/symbiote/silverstripe-queuedjobs/blob/6f2ad28700ac149d61c4e4cff4bb3d4035425799/src/Services/QueuedJobService.php#L462.

@dnsl48 I think we can close this issue now (don't have permissions)
