### ISSUE TITLE
Check that Subsite module installed before checking SubsiteID

### ISSUE THREAD

**Issue by emteknetnz** [symbiote/silverstripe-queuedjobs#245]
This affects 3.1.3

This line on QueuedJobService.php

```
if ($job->SubsiteID && class_exists('Subsite'))
```

Can throw the following error when running a CWP SolrReindex:

> NOTICE: Undefined property: SolrReindexGroupQueuedJob::$SubsiteID

This could probably be easily fixed by changing this above line to

```
if (class_exists('Subsite') && $job->SubsiteID)
```

Note: this was fixed on the SS4 line with:

```
if (class_exists(Subsite::class) && !empty($job->SubsiteID))
```

**Comment by ScopeyNZ** [comment]
Sounds like you've got a good understanding. Want to raise a quick PR targeting the `3.0` branch?

**Comment by emteknetnz** [comment]
https://github.com/symbiote/silverstripe-queuedjobs/pull/246

**Comment by GuySartorelli** [comment]
The pull request was merged - this issue should be closed.
