### ISSUE TITLE
Add website to the stalled job email

### ISSUE THREAD

**Issue by IgorNadj** [symbiote/silverstripe-queuedjobs#25]
Currently the body of the stalled job email is just:

> A job named FullTextSearch Update Job appears to have stalled. It has been paused, please login to check it

It would be good to have a link back to the job queue, or at the very least the website this is occurring on. Currently the only way to find this out is to look at who sent the email by looking at the headers.

Thanks!

## Pull requests

- [ ] https://github.com/silverstripe/cwp-installer/pull/22
- [ ] https://github.com/silverstripe/cwp-recipe-search/pull/7
- [ ] #215

**Comment by robbieaverill** [comment]
Note: try to factor in support for subsites

**Comment by ScopeyNZ** [comment]
Closed in #215
