### ISSUE TITLE
Cronjob specified incorrectly in Quick Usage Overview

### ISSUE THREAD

**Issue by tomstgeorge** [symbiote/silverstripe-queuedjobs#251]
Master branch. In the Quick Usage Overwiew cronjob entry is shown as:

*/1 * * * * php /path/to/silverstripe/vendor/bin/sake dev/tasks/ProcessJobQueueTask

It should be without the php part

*/1 * * * * /path/to/silverstripe/vendor/bin/sake dev/tasks/ProcessJobQueueTask

sake is a shell script not a php script

**Comment by robbieaverill** [comment]
Would you like to make a pull request to update this?

**Comment by tomstgeorge** [comment]
done

**Comment by robbieaverill** [comment]
Thanks, fixed in #252
