### ISSUE TITLE
Remove getRunAsMemberID() from QueuedJob interface

### ISSUE THREAD

**Issue by robbieaverill** [symbiote/silverstripe-queuedjobs#261]
Was added in https://github.com/symbiote/silverstripe-queuedjobs/pull/247, but is a breaking change. We'll need to remove it for the 2.4 minor release.

**Comment by ScopeyNZ** [comment]
The other possibility is that we introduce new interface methods in a new interface. In this case it could be `UserContextInterface` or something - allowing jobs to provide their own "user context".

**Comment by mfendeksilverstripe** [comment]
PR here: https://github.com/symbiote/silverstripe-queuedjobs/pull/262
