### ISSUE TITLE
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by NightJar** [symbiote/silverstripe-queuedjobs#273]
https://github.com/symbiote/silverstripe-queuedjobs/blob/50b962c27f61ad76d07465c799df98704305480a/src/DataObjects/QueuedJobDescriptor.php#L215

```
PHP 7.4.0 (cli) (built: Nov 30 2019 10:43:49) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.8.1, Copyright (c) 2002-2019, by Derick Rethans
```

**Comment by ssmarco** [comment]
Hi @NightJar 
This is related to this https://github.com/symbiote/silverstripe-queuedjobs/pull/271

**Comment by NightJar** [comment]
Thanks Marco, I see it was a bit too late to make the 4.5.0-beta1 tag, although it is in 4.5 branch, so hopefully this means that it'll be in 4.5.0 stable :)
Also, I'll merge it up so the change is visible from `master` too.
