### ISSUE TITLE
Release v4.5 

### ISSUE THREAD

**Issue by brynwhyman** [symbiote/silverstripe-queuedjobs#275]
Can someone please look at doing a 4.5 release of this module? We've had a notable request for this release so to gain PHP7.4 compatibility, [with this commit](https://github.com/symbiote/silverstripe-queuedjobs/pull/271).

**Comment by brynwhyman** [comment]
cc @ssmarco

**Comment by Cheddam** [comment]
[4.5.0 is now available](https://github.com/symbiote/silverstripe-queuedjobs/releases/4.5.0).

**Comment by ssmarco** [comment]
🎉 Thanks Team
