### ISSUE TITLE
Job locking is not thread safe

### ISSUE THREAD

**Issue by mfendeksilverstripe** [symbiote/silverstripe-queuedjobs#280]
Job locking is not thread safe and it project setups which runs multiple instances with multiple job processing threads one job can be picked up by multiple processes.

We should introduce a reliable job locking mechanism.

Fixed in https://github.com/symbiote/silverstripe-queuedjobs/pull/279

**Comment by dnsl48** [comment]
A fix is going to be released in `4.6`
