### ISSUE TITLE
Running queuedjobs in multiple queue processors

### ISSUE THREAD

**Issue by cutdmx2010** [symbiote/silverstripe-queuedjobs#30]
Hi there,

Is it possible to process the queuedjobs in multiple workers? The issue that I currently have is that my backup system adds many many sites to the queuedjobs list and trying to backup 100+ sites on a single thread/worker is very slow and inefficient.

Is there anyway (with modification) this SIlverStripe modular can run on multiple queue processors?

Thanks,

**Comment by nyeholt** [comment]
Maybe - by using the gearman queue worker for capturing and running the jobs as they come in. The problem being that it's an experimental module that hasn't been touched in a while, so I'm not sure if it will actually work at all. If you're happy to dig at code to figure out how things work, it may do what you need. 

https://github.com/nyeholt/silverstripe-gearman
