### ISSUE TITLE
Minor change to GridField iconography

### ISSUE THREAD

**Issue by phptek** [symbiote/silverstripe-queuedjobs#45]
I'm no UX expert but the icon used to represent a job to be paused , looks like a "No Entry" sign. My suggestion is to change the pause icon to look like a pause button does on a CD player, and the current "Reload" icon, while better, should use a "Play" icon - again as per the CD player analogy for consistency.

**Comment by robbieaverill** [comment]
_Improvements_ made at #164, but probably not enough to close this issue.

**Comment by robbieaverill** [comment]
@phptek have you had a chance to check out the new icons in SS4? Thoughts?

**Comment by phptek** [comment]
@robbieaverill Yeah now looks awesome. Closing.
