### ISSUE TITLE
BUG: Unpredictable test execution

### ISSUE THREAD

**Issue by assertchris** [symbiote/silverstripe-queuedjobs#64]
The Travis tests are failing randomly due to what I imagine are environmental or race conditions.

<img width="924" alt="screen shot 2015-09-20 at 4 03 22 pm" src="https://cloud.githubusercontent.com/assets/200609/9979168/41c14074-5fb1-11e5-98b5-d2172fa8191c.png">

<img width="590" alt="screen shot 2015-09-20 at 4 04 30 pm" src="https://cloud.githubusercontent.com/assets/200609/9979169/4b09131e-5fb1-11e5-8fd5-0ddeb23513af.png">

**Comment by robbieaverill** [comment]
I haven't seen this for a while, closing for now
