### ISSUE TITLE
Completed queued jobs in admin

### ISSUE THREAD

**Issue by Firesphere** [symbiote/silverstripe-queuedjobs#99]
Currently, queued jobs "disappear" after they've ran. It would be nice to have a completed jobs section, to view the messages. As people aren't keeping an eye on their system 24/7.

**Comment by tractorcow** [comment]
Yeah that might be nice. Maybe on another tab right? Kind of like how comments module splits "new", "spam", and "moderated" comments into tabs.

**Comment by Firesphere** [comment]
Created a pull request for this. Implemented in a slightly different way because it felt more logical to rename the class to "FinishedJob", as it's not a description of a QueuedJob anymore.

**Comment by robbieaverill** [comment]
For reference the PR is #102
